Implementation/graph summarization for hashtag recommendation
data-boars/hashtag-recommendation-project pull request #8
Opened 2019-03-27 15:44 UTC by kacper1095

2019-03-29 19:01 UTC, mkosturek requested changes
Generalnie: 👍 🥇 
Kilka uwag estetyczno-clean coderskich
Chyba tylko jedna uwaga co do działania - przy sprawdzaniu warunku zbiegania random walka, może być istotna - dlatego "Request Changes".

2019-03-29 19:01 UTC, mkosturek commented on tweet_recommendations/data_processing/tagged_files_to_dataframe.py
> +args = parser.parse_args()
Może lepiej żeby to było w `main`, chociaż nie wiem czy to robi różnicę :)

2019-03-29 19:01 UTC, mkosturek commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +        Removes ending suffix that was used to distinguish between nodes with the same name but different category.
❤️ Bardzo szanuję za dokumentację nawet w tak drobnych metodach...

2019-03-29 19:01 UTC, mkosturek commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +        # ... so this simplifies to cosine similarity
zmieniłbym ten komentarz `... so this simplifies to cosine similarity` na `... so this simplifies calculation of cosine similarity - no normalisation required`
bo trochę wprowadza w błąd, sugerując że z jakiegoś innego wzorku upraszcza nam się coś do cosine similarity, chociaż to nie o to chodzi

2019-03-29 19:01 UTC, mkosturek commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +            diff = np.abs(np.sum(similarity_rank_vertices - previous_similarity_rank_vertices))
hmm.. nie wiem czy nie lepiej byłoby zrobić na odwrót. Zamiast `np.abs(np.sum(...))`, zrobić: `np.sum(np.abs(...))`
W tej chwili może dojść do sytuacji:
`previous_similarity_rank_vertices = [1,-1]`
`similarity_rank_vertices = [-1,1]` ( zmiana o 180 stopni)
`d = (similarity_rank_vertices - previous_similarity_rank_vertices) = [-2, 2]`
`s = sum(d) = 0`
`diff = abs(s) = 0`

w tym co proponuję wyszłoby:
`a = abs(d) = [2, 2]`
`diff = sum(a) = 4`
Czyli wykażemy, że jeszcze się coś zmienia i jeszcze nie zbiegło

2019-03-29 19:01 UTC, mkosturek commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +            previous_similarity_rank_vertices = similarity_rank_vertices
Dla przejrzystości przypisanie `previous_similarity_rank_vertices = similarity_rank_vertices` robiłbym raczej na początku kroku pętli a nie na końcu, chyba że są jakieś ku temu powody, których nie widzę :)

2019-03-29 19:01 UTC, mkosturek commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +                    print("Random walk did not converged, current error: {:.6f}".format(diff))
`did not converged` -> `did not converge` :P

2019-03-29 19:01 UTC, mkosturek commented on tweet_recommendations/other_methods/lemmatizer.py
> +class TaggerToygerLemmatizer(TransformerMixin, BaseEstimator):
Rozumiem że to kod, który już wcześniej był gdzieś wykorzystywany, ale zaginął i raczej nie ma potrzeby go przeglądać? :P

2019-03-29 19:01 UTC, mkosturek commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +                            if self.graph.node[other_node]["type"] == "hashtag" and not self.graph.has_edge(node,
nie ma sprawdzania czy `other node == node` czyli czy nie łączymy hashtaga samego ze sobą.
Wiem, że potem w incidence matrix diagonala jest zerowana, ale może warto już tutaj o to zadbać żeby mieć spójny graf i incidence matrix. - Propozycja, nie przymus.

2019-03-29 19:01 UTC, mkosturek commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +        incidence_matrix = self._get_binary_incidence_matrix()[:len(self._hashtag_labels), len(self._hashtag_labels):]
`[:len(self._hashtag_labels), len(self._hashtag_labels):]` - zastanawia mnie to indeksowanie, że na jednym wymiarze jest `: len` a na drugim `len :` - czy to na pewno poprawne?

2019-03-29 19:01 UTC, mkosturek commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +        weighted_degree = np.asarray(list(map(itemgetter(1), hashtag_graph.degree(weight="weight"))))
rozumiem że `nx.from_scipy_sparse_matrix(weighted_adjacency_matrix_of_tags)` buduje graf gdzie każda krawędź m atrybut "weight" zgodny z wartościami w `weighted_adjacency_matrix_of_tags`? i stąd bierze się `hashtag_graph.degree(weight="weight")` ?

I `hashtag_graph.degree(...)` zwraca wyniki w ustalonej kolejności węzłów, a nie przetasowuje je?

2019-03-29 19:01 UTC, mkosturek commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +        while True:
Możnaby wydzielić random walka do osobnej metody, ale jeśli wyjdzie dużo argumentów i dużo wyjść to może nie ma to sensu... wtedy ew komentarz że tu się zaczyna random walk

2019-03-29 19:23 UTC, kacper1095 commented on tweet_recommendations/other_methods/lemmatizer.py
> +class TaggerToygerLemmatizer(TransformerMixin, BaseEstimator):
Bardziej to służy do wykorzystania lemmatów zrobiony przez TaggeraToygera niż do działania taggera toygera

2019-03-29 19:32 UTC, kacper1095 commented on tweet_recommendations/data_processing/tagged_files_to_dataframe.py
> +args = parser.parse_args()
O tyle nie, że mógłbyś zaimportować ten skrypt i użyć jedną z metod tam zawartych. Argument Parser trochę Cię blokuje przed tym w tym momencie i przynajmniej u mnie oznacza tyle, że skrypt jest samowystarczalny i nie powinien być używany nigdzie indziej

2019-03-29 19:32 UTC, kacper1095 commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +        Removes ending suffix that was used to distinguish between nodes with the same name but different category.
^_^

2019-03-29 19:35 UTC, kacper1095 commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +                    print("Random walk did not converged, current error: {:.6f}".format(diff))
Pytanie: w emfazie też DID niweluje czas przeszły czasownika?

2019-03-29 19:43 UTC, kacper1095 commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +        incidence_matrix = self._get_binary_incidence_matrix()[:len(self._hashtag_labels), len(self._hashtag_labels):]
Poprawnie, bo chcesz uzyskać macierz: 
![image](https://user-images.githubusercontent.com/16157910/55258394-00ca2b00-5263-11e9-9c54-63170a4793b3.png)
Jakby nie patrzeć, to w kodzie `_get_binary_incidence_matrix` macierz jest tworzona według labelek na podstawie `nodelist`:
![image](https://user-images.githubusercontent.com/16157910/55258459-29eabb80-5263-11e9-80fb-b0b7cd0ceb83.png)
Więc żeby to zadziałało, to z wierszy trzeba wziąć pierwsze H elementów a z kolumn T + U

2019-03-29 19:46 UTC, kacper1095 commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +        weighted_degree = np.asarray(list(map(itemgetter(1), hashtag_graph.degree(weight="weight"))))
Na podstawie przykładu: https://networkx.github.io/documentation/stable/reference/classes/generated/networkx.Graph.degree.html sądzę, że nie. Sprawdzałem osobiście, zawsze listuje je od 0 do N.

2019-03-29 19:50 UTC, kacper1095 commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +            diff = np.abs(np.sum(similarity_rank_vertices - previous_similarity_rank_vertices))
Racja, zawsze piszę jak mówisz, a tutaj wyszło pisanie na szybko :)

2019-03-29 20:37 UTC, mkosturek commented on tweet_recommendations/other_methods/graph_summarization_for_hashtag_recommendation.py
> +        incidence_matrix = self._get_binary_incidence_matrix()[:len(self._hashtag_labels), len(self._hashtag_labels):]
Już rozumiem, zgadza się :+1:

2019-03-29 20:41 UTC, mkosturek approved these changes
Wszystko gra

2019-03-31 19:51 UTC, jmichalowski12 commented on tweet_recommendations/validators/graph_summarization_validator.py
> +print(the_graph.transform("Wiozę szwagra na wybory")[:10])
Fajnie, że są te printy, ale nie wiem, czy powinny trafić do mastera)

2019-03-31 19:55 UTC, jmichalowski12 commented
Co do uwag estetycznych to proponuję sobie [black'a](https://github.com/ambv/black) zaisntalować.
On rozwiązuje wątpliwości i ręczne pilnowanie zgodności z PEP8 - nie uważam, że przeformatowany kod trzymający się pepa 1 do 1 jest najczytelniejszy - ale rozwiąże nam to problem spójności formatowania plików

Inna uwaga jest to o czym rozmawialiśmy - to kodzenie w stylu sklearnowym dla mnie zaciemnia trochę działanie całości, ale biorąc pod uwagę, że ktoś może zechcieć z tego korzystać to dobrze jest taką strukturę utrzymać, żeby nikt się nie musiał zastanawiać jak z tego korzystać.

2019-04-01 05:45 UTC, kacper1095 commented
Sam pilnuję formatowania PEP8, w pycharmie jest taka opcja. Na razie na podstawie widzianego kodu to odnoszę wrażenie, że black to najgorszy sort formatowania i nie będę tego instalował. W dodatku on nie przestrzega PEP8. Co najwyżej mogę się zgodzić na flake8, który już tego formatowania przestrzega

2019-04-01 12:04 UTC, jmichalowski12 approved these changes

2019-04-01 20:01 UTC, merged